#pragma once
#include <unordered_map>
#include <string>
#include <cstdint>

// wled_effect_map.h — WLED effect/palette name -> ID maps.
//
// AUTO-GENERATED from WLED v0.14.x FX.cpp's JSON_mode_names[] and
// palettes.h -- see tools/generate_wled_maps.py, which regenerates this
// file from a checked-out WLED source tree. DO NOT EDIT MANUALLY.
//
// Effect/palette IDs are STABLE within a WLED minor version but may shift
// across major versions -- this map is version-locked to 0.14.x. Regenerate
// (and re-review the .show/Fennel scripts that name effects by string) when
// bumping the target WLED version.
//
// `inline` (not `static`/plain `const`) so every translation unit that
// includes this header shares one definition instead of each getting its
// own private copy of two ~190/~75-entry hash maps -- this header is
// pulled into several device .cpp files via wled_manager.cpp.

namespace wled {

inline constexpr uint16_t EFFECT_COUNT = 187;
inline constexpr uint16_t PALETTE_COUNT = 71;

// Effect name -> ID mapping (kebab-case names).
inline const std::unordered_map<std::string, uint8_t> EFFECT_MAP = {
    {"solid", 0},
    {"blink", 1},
    {"breathe", 2},
    {"wipe", 3},
    {"wipe-random", 4},
    {"random-colors", 5},
    {"sweep", 6},
    {"dynamic", 7},
    {"colorloop", 8},
    {"rainbow", 9},
    {"scan", 10},
    {"dual-scan", 11},
    {"fade", 12},
    {"theater", 13},
    {"theater-rainbow", 14},
    {"running", 15},
    {"saw", 16},
    {"twinkle", 17},
    {"dissolve", 18},
    {"dissolve-rnd", 19},
    {"sparkle", 20},
    {"sparkle-dark", 21},
    {"sparkle+", 22},
    {"strobe", 23},
    {"strobe-rainbow", 24},
    {"strobe-mega", 25},
    {"blink-rainbow", 26},
    {"android", 27},
    {"chase", 28},
    {"chase-random", 29},
    {"chase-rainbow", 30},
    {"chase-flash", 31},
    {"chase-flash-rnd", 32},
    {"rainbow-runner", 33},
    {"colorful", 34},
    {"traffic-light", 35},
    {"sweep-random", 36},
    {"running-2", 37},
    {"aurora", 38},
    {"stream", 39},
    {"scanner", 40},
    {"lighthouse", 41},
    {"fireworks", 42},
    {"rain", 43},
    {"merry-christmas", 44},
    {"fire-flicker", 45},
    {"gradient", 46},
    {"loading", 47},
    {"police", 48},
    {"police-all", 49},
    {"two-dots", 50},
    {"two-areas", 51},
    {"circus", 52},
    {"halloween", 53},
    {"tri-chase", 54},
    {"tri-wipe", 55},
    {"tri-fade", 56},
    {"lightning", 57},
    {"icu", 58},
    {"multi-comet", 59},
    {"scanner-dual", 60},
    {"stream-2", 61},
    {"oscillate", 62},
    {"pride-2015", 63},
    {"juggle", 64},
    {"palette", 65},
    {"fire-2012", 66},
    {"colorwaves", 67},
    {"bpm", 68},
    {"fill-noise", 69},
    {"noise-1", 70},
    {"noise-2", 71},
    {"noise-3", 72},
    {"noise-4", 73},
    {"colortwinkles", 74},
    {"lake", 75},
    {"meteor", 76},
    {"meteor-smooth", 77},
    {"railway", 78},
    {"ripple", 79},
    {"twinklefox", 80},
    {"twinklecat", 81},
    {"halloween-eyes", 82},
    {"solid-pattern", 83},
    {"solid-pattern-tri", 84},
    {"spots", 85},
    {"spots-fade", 86},
    {"glitter", 87},
    {"candle", 88},
    {"fireworks-starburst", 89},
    {"fireworks-1d", 90},
    {"bouncing-balls", 91},
    {"sinelon", 92},
    {"sinelon-dual", 93},
    {"sinelon-rainbow", 94},
    {"popcorn", 95},
    {"drip", 96},
    {"plasma", 97},
    {"percent", 98},
    {"ripple-rainbow", 99},
    {"heartbeat", 100},
    {"pacifica", 101},
    {"candle-multi", 102},
    {"solid-glitter", 103},
    {"sunrise", 104},
    {"phased", 105},
    {"twinkleup", 106},
    {"noise-pal", 107},
    {"sine", 108},
    {"phased-noise", 109},
    {"flow", 110},
    {"chunchun", 111},
    {"dancing-shadows", 112},
    {"washing-machine", 113},
    {"candy-cane", 114},
    {"blends", 115},
    {"tv-simulator", 116},
    {"dynamic-smooth", 117},
    {"spaceships", 118},
    {"crazy-bees", 119},
    {"ghost-rider", 120},
    {"blobs", 121},
    {"scrolling-text", 122},
    {"drift-rose", 123},
    {"distortion-waves", 124},
    {"soap", 125},
    {"octopus", 126},
    {"waving-cell", 127},
    {"pixels", 128},
    {"pixelwave", 129},
    {"juggles", 130},
    {"matripix", 131},
    {"gravimeter", 132},
    {"plasmoid", 133},
    {"puddles", 134},
    {"midnoise", 135},
    {"noisemeter", 136},
    {"freqwave", 137},
    {"freqmatrix", 138},
    {"spectral", 139},
    {"waterfall", 140},
    {"waterfall-2", 141},
    {"freqpixels", 142},
    {"noisefire", 143},
    {"puddlepeak", 144},
    {"noisemove", 145},
    {"noise2d", 146},
    {"perlin-move", 147},
    {"ripple-peak", 148},
    {"firenoise", 149},
    {"squared-swirl", 150},
    {"funky-plank", 151},
    {"dna", 152},
    {"matrix", 153},
    {"meteor-rain", 154},
    {"plasma-2d", 155},
    {"gravcenter", 156},
    {"gravcentric", 157},
    {"gravfreq", 158},
    {"dj-light", 159},
    {"funky-plank-2", 160},
    {"pulser", 161},
    {"pulser-2", 162},
    {"blurz", 163},
    {"drift", 164},
    {"waverly", 165},
    {"sun-radiation", 166},
    {"colored-bursts", 167},
    {"julia", 168},
    {"game-of-life", 169},
    {"tartan", 170},
    {"polar-lights", 171},
    {"swirl", 172},
    {"tartan-2", 173},
    {"drift-2", 174},
    {"swirl-2", 175},
    {"pixel-2d", 176},
    {"noise-2d", 177},
    {"plasma-ball", 178},
    {"fireworks-2d", 179},
    {"hiphotic", 180},
    {"sindots", 181},
    {"dna-spiral", 182},
    {"black-hole", 183},
    {"wavesins", 184},
    {"rocktaves", 185},
    {"akemi", 186},
};

// Palette name -> ID mapping (kebab-case names).
inline const std::unordered_map<std::string, uint8_t> PALETTE_MAP = {
    {"default", 0},
    {"random-cycle", 1},
    {"color-1", 2},
    {"colors-1-2", 3},
    {"color-gradient", 4},
    {"colors-only", 5},
    {"party", 6},
    {"cloud", 7},
    {"lava", 8},
    {"ocean", 9},
    {"forest", 10},
    {"rainbow", 11},
    {"rainbow-bands", 12},
    {"sunset", 13},
    {"rivendell", 14},
    {"breeze", 15},
    {"red-blue", 16},
    {"yellowout", 17},
    {"analogous", 18},
    {"splash", 19},
    {"pastel", 20},
    {"sunset-2", 21},
    {"beach", 22},
    {"vintage", 23},
    {"departure", 24},
    {"landscape", 25},
    {"beech", 26},
    {"sherbet", 27},
    {"hult", 28},
    {"hult-64", 29},
    {"drywet", 30},
    {"jul", 31},
    {"grintage", 32},
    {"rewhi", 33},
    {"tertiary", 34},
    {"fire", 35},
    {"icefire", 36},
    {"cyane", 37},
    {"light-pink", 38},
    {"autumn", 39},
    {"magenta", 40},
    {"magred", 41},
    {"yelmag", 42},
    {"yelblu", 43},
    {"orange-teal", 44},
    {"tiamat", 45},
    {"april-night", 46},
    {"orangery", 47},
    {"c9", 48},
    {"sakura", 49},
    {"aurora", 50},
    {"atlantica", 51},
    {"c9-2", 52},
    {"c9-new", 53},
    {"temperature", 54},
    {"aurora-2", 55},
    {"retro-clown", 56},
    {"candy", 57},
    {"toxy-reef", 58},
    {"fairy-reef", 59},
    {"semi-blue", 60},
    {"pink-candy", 61},
    {"red-reef", 62},
    {"aqua-flash", 63},
    {"yelblu-hot", 64},
    {"lite-light", 65},
    {"red-flash", 66},
    {"blink-red", 67},
    {"red-shift", 68},
    {"red-tide", 69},
    {"candy-2", 70},
};

// Safe lookups. Return false (leave `out` unmodified) for an unknown name --
// the caller decides fallback + logging policy (see wled_manager.cpp, which
// falls back to solid/default and logs a warning, mirroring
// capFromName's contract in provision.cpp).
inline bool effectIdFromName(const std::string& name, uint8_t& out) {
  auto it = EFFECT_MAP.find(name);
  if (it == EFFECT_MAP.end()) return false;
  out = it->second;
  return true;
}

inline bool paletteIdFromName(const std::string& name, uint8_t& out) {
  auto it = PALETTE_MAP.find(name);
  if (it == PALETTE_MAP.end()) return false;
  out = it->second;
  return true;
}

}  // namespace wled
